packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@studyzy/openspec-cn'
  - esbuild
  - msgpackr-extract
  - prisma
  - unrs-resolver
